
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Migrations need advisory locks, which Neon's pooled (PgBouncer) endpoint doesn't
    // support reliably, so the CLI uses the direct host. The app keeps DATABASE_URL.
    url: process.env.DATABASE_URL_UNPOOLED || env("DATABASE_URL").replace("-pooler.", "."),
  },
});
